# Generated by Django 5.2 on 2026-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('PREP', 'Preparatory'), ('SECONDARY', 'Secondary'), ('UNIVERSITY', 'University')], max_length=20, null=True),
        ),
    ]
