# Generated by Django 5.2 on 2026-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('GRADE_1_PRIMARY', 'أولى ابتدائي'), ('GRADE_2_PRIMARY', 'تانية ابتدائي'), ('GRADE_3_PRIMARY', 'تالتة ابتدائي'), ('GRADE_4_PRIMARY', 'رابعة ابتدائي'), ('GRADE_5_PRIMARY', 'خامسة ابتدائي'), ('GRADE_6_PRIMARY', 'سادسة ابتدائي'), ('GRADE_1_PREPARATORY', 'أولى إعدادي'), ('GRADE_2_PREPARATORY', 'تانية إعدادي'), ('GRADE_3_PREPARATORY', 'تالتة إعدادي'), ('GRADE_1_SECONDARY', 'أولى ثانوي'), ('GRADE_2_SECONDARY', 'تانية ثانوي'), ('GRADE_3_SECONDARY', 'تالتة ثانوي'), ('UNIVERSITY', 'جامعة')], max_length=30, null=True),
        ),
    ]
