# Generated by Django 5.2 on 2026-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_examattemptanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='exams/questions/'),
        ),
    ]
