# Generated by Django 5.2 on 2026-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_examquestion_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
