# Generated by Django 5.2 on 2026-08-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_bunny_solution_video_id_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='assignment_pdf',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_pdf',
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='bunny_assignment_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
