# Generated by Django 5.2 on 2026-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lesson_assignment_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
