# Generated by Django 5.2 on 2026-08-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lessonquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
